# Generated by Django 4.0.6 on 2022-07-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='accountId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userm'),
        ),
    ]
