# Generated by Django 4.0.6 on 2022-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_opportunity_accountid_opportunity_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='accountId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
