# Generated by Django 4.0.6 on 2022-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_opportunity_accountid_alter_opportunity_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
